name: Run unit tests
on: [push, workflow_call]
    
permissions:
  contents: read

jobs:
  # Run unit tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        #with:
        # Fetch all history for all tags and branches
        # Needed for getting git rev-list for versioning
          #fetch-depth: 0
          
      - name: Get java
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2.5.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@fa522696baadfef7de0fe810135f446221e665c2 # 3.7
        with:
          cli: 1.10.3.1075 # Clojure CLI based on tools.deps

      - name: Run Unit tests & abort action if tests fail
        run: clojure -X:test
        
